from __future__ import annotations

from ..domain.operations import Operation

_PROMPT = {"type": "string", "maxLength": 8000}
_ASSET = {"type": "object", "required": ["asset_id"], "properties": {"asset_id": {"type": "string"}}}
_SEED = {"type": "integer", "minimum": 0, "maximum": 2147483647}
_STEPS = {"type": "integer", "minimum": 1, "maximum": 80}

IMAGE_PRESETS = ["draft", "balanced", "master", "character_master"]
VIDEO_PRESETS = ["draft", "balanced", "master"]
GENERIC = ["draft", "balanced", "master"]


def all_operations() -> list[Operation]:
    return [
        Operation(
            id="image.generate",
            description="Generate an image from a text prompt.",
            presets=IMAGE_PRESETS,
            input_schema={
                "type": "object",
                "required": ["prompt"],
                "properties": {
                    "prompt": _PROMPT,
                    "negative_prompt": _PROMPT,
                    "width": {"type": "integer"},
                    "height": {"type": "integer"},
                    "aspect_ratio": {"type": "string"},
                    "candidate_count": {"type": "integer", "minimum": 1, "maximum": 8},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS, "cfg": {"type": "number"}, "loras": {"type": "array"}}},
            implemented=True,
            required_models=["qwen-image-2512-fp8"],
            capability_path=("image", "generate"),
        ),
        Operation(
            id="image.edit",
            description="Edit an image with natural-language instructions or merge 2–3 references.",
            presets=["draft", "balanced", "master", "identity_strict"],
            input_schema={
                "type": "object",
                "required": ["prompt"],
                "properties": {
                    "prompt": _PROMPT,
                    "reference_images": {"type": "array", "minItems": 1, "maxItems": 3, "items": _ASSET},
                    "image": _ASSET,
                    "negative_prompt": _PROMPT,
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS, "cfg": {"type": "number"}}},
            implemented=True,
            required_models=["qwen-image-edit-2511-fp8"],
            capability_path=("image", "edit"),
        ),
        Operation(
            id="image.controlled",
            description="Controlled image generation (depth, pose, canny).",
            presets=GENERIC,
            input_schema={
                "type": "object",
                "required": ["prompt", "control_image"],
                "properties": {
                    "prompt": _PROMPT,
                    "control_image": _ASSET,
                    "control_type": {"type": "string", "enum": ["pose", "depth", "canny"]},
                    "control_strength": {"type": "number", "minimum": 0, "maximum": 2},
                    "negative_prompt": _PROMPT,
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS, "cfg": {"type": "number"}}},
            implemented=True,
            required_models=["qwen-image-2512-fp8", "qwen-controlnet-2512-fun-union"],
            capability_path=("image", "control"),
        ),
        Operation(
            id="image.layered",
            description="Decompose an image into RGBA layers (Qwen-Image-Layered).",
            presets=GENERIC,
            input_schema={
                "type": "object",
                "required": ["image"],
                "properties": {
                    "image": _ASSET,
                    "prompt": _PROMPT,
                    "layers": {"type": "integer", "minimum": 1, "maximum": 8},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS, "cfg": {"type": "number"}}},
            implemented=True,
            required_models=["qwen-image-layered"],
            capability_path=("image", "layered"),
        ),
        Operation(id="image.mask", description="Generate a mask (SAM).", presets=GENERIC, input_schema={}, parameter_schema={}, capability_path=("image", "mask")),
        Operation(id="image.depth", description="Generate a depth map.", presets=GENERIC, input_schema={}, parameter_schema={}, capability_path=("image", "depth")),
        Operation(
            id="image.upscale",
            description="Conservative image upscale.",
            presets=["draft", "balanced", "master", "conservative_upscale"],
            input_schema={"type": "object", "required": ["image"], "properties": {"image": _ASSET, "scale": {"type": "integer", "enum": [2, 4]}}},
            parameter_schema={},
            implemented=True,
            required_models=["upscalers-esrgan"],
            capability_path=("image", "upscale"),
        ),
        Operation(id="image.inspect", description="Inspect image metadata.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(
            id="video.generate",
            description="Generate video from text.",
            presets=VIDEO_PRESETS,
            input_schema={
                "type": "object",
                "required": ["prompt"],
                "properties": {
                    "prompt": _PROMPT,
                    "negative_prompt": _PROMPT,
                    "audio_prompt": _PROMPT,
                    "duration_seconds": {"type": "number", "minimum": 1, "maximum": 30},
                    "aspect_ratio": {"type": "string"},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS}},
            implemented=True,
            required_models=["ltx-2.5-distilled"],
            capability_path=("video", "text_to_video"),
        ),
        Operation(
            id="video.image_to_video",
            description="Generate video from a start image.",
            presets=VIDEO_PRESETS,
            input_schema={
                "type": "object",
                "required": ["start_image", "prompt"],
                "properties": {
                    "start_image": _ASSET,
                    "prompt": _PROMPT,
                    "audio_prompt": _PROMPT,
                    "duration_seconds": {"type": "number", "minimum": 1, "maximum": 30},
                    "aspect_ratio": {"type": "string"},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS}},
            implemented=True,
            required_models=["ltx-2.5-distilled"],
            capability_path=("video", "image_to_video"),
        ),
        Operation(
            id="video.audio_to_video",
            description="Generate video conditioned on an uploaded audio clip.",
            presets=VIDEO_PRESETS,
            input_schema={
                "type": "object",
                "required": ["audio", "prompt"],
                "properties": {
                    "audio": _ASSET,
                    "prompt": _PROMPT,
                    "start_image": _ASSET,
                    "end_image": _ASSET,
                    "duration_seconds": {"type": "number", "minimum": 1, "maximum": 30},
                    "aspect_ratio": {"type": "string"},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS}},
            implemented=True,
            required_models=["ltx-2.5-distilled"],
            capability_path=("video", "audio_to_video"),
        ),
        Operation(
            id="video.first_last_frames",
            description="Generate video between a first and last frame.",
            presets=VIDEO_PRESETS,
            input_schema={
                "type": "object",
                "required": ["start_image", "end_image", "prompt"],
                "properties": {
                    "start_image": _ASSET,
                    "end_image": _ASSET,
                    "prompt": _PROMPT,
                    "audio_prompt": _PROMPT,
                    "duration_seconds": {"type": "number", "minimum": 1, "maximum": 30},
                    "aspect_ratio": {"type": "string"},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS}},
            implemented=True,
            required_models=["ltx-2.5-distilled"],
            capability_path=("video", "first_last_frames"),
        ),
        Operation(id="video.continue", description="Continue a video from the previous clip.", presets=VIDEO_PRESETS, input_schema={}, parameter_schema={}, capability_path=("video", "continuation")),
        Operation(id="video.enhance", description="Restore or enhance a video.", presets=GENERIC, input_schema={}, parameter_schema={}, capability_path=("video", "enhancement")),
        Operation(id="video.interpolate", description="Frame interpolation.", presets=GENERIC, input_schema={}, parameter_schema={}, capability_path=("video", "interpolation")),
        Operation(
            id="video.lipsync",
            description="Lip-sync a start image (optional end/middle frames) to uploaded audio.",
            presets=VIDEO_PRESETS,
            input_schema={
                "type": "object",
                "required": ["audio", "start_image", "prompt"],
                "properties": {
                    "audio": _ASSET,
                    "start_image": _ASSET,
                    "end_image": _ASSET,
                    "middle_image": _ASSET,
                    "prompt": _PROMPT,
                    "duration_seconds": {"type": "number", "minimum": 1, "maximum": 30},
                    "aspect_ratio": {"type": "string"},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS}},
            implemented=True,
            required_models=["ltx-2.5-distilled", "ltx-iclora-lipdub"],
            capability_path=("video", "lipsync"),
        ),
        Operation(
            id="video.motion_transfer",
            description="Transfer motion from a reference video.",
            presets=VIDEO_PRESETS,
            input_schema={
                "type": "object",
                "required": ["reference_video", "prompt"],
                "properties": {
                    "reference_video": _ASSET,
                    "start_image": _ASSET,
                    "prompt": _PROMPT,
                    "audio_prompt": _PROMPT,
                    "duration_seconds": {"type": "number", "minimum": 1, "maximum": 30},
                    "aspect_ratio": {"type": "string"},
                },
            },
            parameter_schema={"properties": {"seed": _SEED, "steps": _STEPS}},
            implemented=True,
            required_models=["ltx-2.5-distilled", "ltx-iclora-motion-track"],
            capability_path=("video", "motion_transfer"),
        ),
        Operation(id="video.extract_frame", description="Extract a frame from video.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="video.inspect", description="Inspect video metadata.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="video.mask", description="Video mask / tracking.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="audio.tts", description="Text to speech.", presets=["narrator_hindi", "dialogue_hindi", "draft", "master"], input_schema={}, parameter_schema={}, capability_path=("audio", "tts")),
        Operation(id="audio.sfx", description="Isolated sound effect.", presets=GENERIC, input_schema={}, parameter_schema={}, capability_path=("audio", "sfx")),
        Operation(id="audio.ambience", description="Ambience stem.", presets=GENERIC, input_schema={}, parameter_schema={}, capability_path=("audio", "ambience")),
        Operation(id="audio.music", description="Music generation.", presets=["draft", "cinematic_master"], input_schema={}, parameter_schema={}, capability_path=("audio", "music")),
        Operation(id="audio.mix", description="Mix audio stems on a timeline.", presets=["cinematic", "master"], input_schema={}, parameter_schema={}, capability_path=("audio", "mix")),
        Operation(id="audio.inspect", description="Inspect audio metadata.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="media.concat", description="Concatenate clips.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="media.finalize", description="Final mux and delivery encode.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="qc.image", description="Image quality checks.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="qc.video", description="Video quality checks.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="qc.audio", description="Audio quality checks.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(id="qc.media", description="Combined media quality checks.", presets=GENERIC, input_schema={}, parameter_schema={}),
        Operation(
            id="text.chat",
            description="Synchronous text + vision chat via llama-server. Not a Comfy job.",
            presets=GENERIC,
            input_schema={
                "type": "object",
                "required": ["messages"],
                "properties": {
                    "model": {"type": "string"},
                    "messages": {"type": "array"},
                    "temperature": {"type": "number"},
                    "max_tokens": {"type": "integer"},
                    "stream": {"type": "boolean"},
                },
            },
            parameter_schema={},
            implemented=True,
            capability_path=("text", "chat"),
        ),
    ]
